export const BaseHeroVisibilityModels = [
  {
    name: "Default",
    model: {
      salePrice: true,
      summonedTime: false,
      id: true,
      rarity: true,
      mainClass: true,
      "R1.mainClass": false,
      "Class+": false,
      subClass: true,
      "R1 Subclass": false,
      "Subclass+": false,
      level: true,
      XP: false,
      XPC: false,
      XPM: false,
      shiny: false,
      generation: true,
      summons: true,
      "gen|sum": false,
      hp: false,
      mp: false,
      statBoost1: true,
      SB1R1: false,
      "sb1+": false,
      statBoost2: true,
      sb2r1: false,
      "sb2+": false,
      TrainStat: true,
      profession: true,
      professionRecessives: false,
      profR1: false,
      pjStatus: true,
      tostat: false,
      statgain: false,
      "Stamina Max": false,
      "Stamina Current": false,
      Stamina: false,
      "Stamina Max In": false,
      sFullAt: false,
      "Profession Stats": false,
      "Skill Profession Stats": false,
      element: true,
      "R1 Element": false,
      "element+": false,
      classScore: true,
      "cScore/J": false,
      growthScore: true,
      "gScore/J": false,
      active1: true,
      a1r1: false,
      "active1+": false,
      active2: true,
      a2r1: false,
      "active2+": false,
      passive1: true,
      p1r1: false,
      "passive1+": false,
      passive2: true,
      p2r1: false,
      "passive2+": false,
      statsUnknown1: false,
      su1r1: false,
      "SU1+": false,
      statsUnknown2: false,
      SU2R1: false,
      "SU2+": false,
      mining: false,
      foraging: false,
      fishing: false,
      gardening: false,
      strength: false,
      dexterity: false,
      agility: false,
      vitality: false,
      endurance: false,
      intelligence: false,
      wisdom: false,
      luck: false,
      previousOwner: false,
      previousOwnerAddress: false,
      owner: false,
      ownerAddress: false,
      name: true,
    },
  },
  {
    name: "Summoning",
    model: {
      salePrice: true,
      summonedTime: false,
      id: true,
      rarity: false,
      mainClass: false,
      "R1.mainClass": false,
      "Class+": true,
      subClass: false,
      "R1 Subclass": false,
      "Subclass+": true,
      level: true,
      XP: false,
      XPC: false,
      XPM: false,
      shiny: false,
      generation: false,
      summons: false,
      "gen|sum": true,
      hp: false,
      mp: false,
      statBoost1: false,
      SB1R1: false,
      "sb1+": true,
      statBoost2: false,
      sb2r1: false,
      "sb2+": true,
      TrainStat: false,
      profession: false,
      professionRecessives: true,
      profR1: false,
      pjStatus: false,
      tostat: false,
      statgain: false,
      "Stamina Max": false,
      "Stamina Current": false,
      Stamina: false,
      "Stamina Max In": false,
      sFullAt: false,
      "Profession Stats": false,
      "Skill Profession Stats": false,
      element: false,
      "R1 Element": false,
      "element+": true,
      classScore: false,
      "cScore/J": false,
      growthScore: true,
      "gScore/J": false,
      active1: false,
      a1r1: false,
      "active1+": true,
      active2: false,
      a2r1: false,
      "active2+": true,
      passive1: false,
      p1r1: false,
      "passive1+": true,
      passive2: false,
      p2r1: false,
      "passive2+": true,
      statsUnknown1: false,
      su1r1: false,
      "SU1+": false,
      statsUnknown2: false,
      SU2R1: false,
      "SU2+": false,
      mining: false,
      foraging: false,
      fishing: false,
      gardening: false,
      strength: false,
      dexterity: false,
      agility: false,
      vitality: false,
      endurance: false,
      intelligence: false,
      wisdom: false,
      luck: false,
      previousOwner: false,
      previousOwnerAddress: false,
      owner: false,
      ownerAddress: false,
      name: false,
    },
  },
  {
    name: "Stats",
    model: {
      salePrice: true,
      summonedTime: false,
      id: true,
      rarity: true,
      mainClass: true,
      "R1.mainClass": false,
      "Class+": false,
      subClass: true,
      "R1 Subclass": false,
      "Subclass+": false,
      level: true,
      XP: false,
      XPC: false,
      XPM: false,
      shiny: false,
      generation: true,
      summons: true,
      "gen|sum": false,
      hp: false,
      mp: false,
      statBoost1: false,
      SB1R1: false,
      "sb1+": false,
      statBoost2: false,
      sb2r1: false,
      "sb2+": false,
      TrainStat: true,
      profession: true,
      professionRecessives: false,
      profR1: false,
      pjStatus: true,
      tostat: true,
      statgain: true,
      "Stamina Max": false,
      "Stamina Current": false,
      Stamina: false,
      "Stamina Max In": false,
      sFullAt: false,
      "Profession Stats": false,
      "Skill Profession Stats": false,
      element: true,
      "R1 Element": false,
      "element+": false,
      classScore: true,
      "cScore/J": false,
      growthScore: true,
      "gScore/J": false,
      active1: false,
      a1r1: false,
      "active1+": false,
      active2: false,
      a2r1: false,
      "active2+": false,
      passive1: false,
      p1r1: false,
      "passive1+": false,
      passive2: false,
      p2r1: false,
      "passive2+": false,
      statsUnknown1: false,
      su1r1: false,
      "SU1+": false,
      statsUnknown2: false,
      SU2R1: false,
      "SU2+": false,
      mining: false,
      foraging: false,
      fishing: false,
      gardening: false,
      strength: true,
      dexterity: true,
      agility: true,
      vitality: true,
      endurance: true,
      intelligence: true,
      wisdom: true,
      luck: true,
      previousOwner: false,
      previousOwnerAddress: false,
      owner: false,
      ownerAddress: false,
      name: false,
    },
  },
];
