export const BasePetVisibilityModels = [
  {
    name: "Default",
    model: {
      salePrice: true,
      id: true,
      rarity: true,
      shiny: false,
      appearance: false,
      appearanceRarity: false,
      displayName: true,
      variant: true,
      family: true,
      backgroundName: true,
      profBonus: true,
      craftBonus: true,
      combatBonus: true,
      eggType: true,
      pool: true,
      credits: true,
      element: true,
      previousOwner: false,
      previousOwnerAddress: false,
      owner: false,
      ownerAddress: false,
      name: false,
    },
  },
];
