export const BaseWeaponVisibilityModels = [
  {
    name: "Default",
    model: {
      salePrice: true,
      currentRealm: false,
      id: true,
      rarity: true,
      weaponTypeName: true,
      displayName: true,
      equipRequirement: true,
      speedModifier: true,
      attack: true,
      baseDamage: false,
      maxDamage: false,
      accuracyRequirement: true,
      pAccuracyAtRequirement: true,
      spell: true,
      basePotency: false,
      maxPotency: false,
      focusRequirement: true,
      mAccuracyAtRequirement: true,
      durabilityRemaining: false,
      maxDurability: false,
      durability: true,
      remainingRepairs: false,
      maxRepairs: false,
      repairs: true,
      restorationCount: false,
      bonusText1: true,
      bonusScalar1: false,
      bonusText2: true,
      bonusScalar2: false,
      bonusText3: true,
      bonusScalar3: false,
      bonusText4: true,
      bonusScalar4: false,
      owner: true,
      ownerAddress: false
    },
  },
];
