const { default: PJBadge } = require("../Components/Hero/PJBadge");

module.exports = {
  Targets: [
    { value: "All", label: "Find" },
    { value: "Tavern", label: "Buy" },
    { value: "Hire", label: "Hire" },
  ],
  Backgrounds: [
    { value: "arctic", label: "Arctic" },
    { value: "city", label: "City" },
    { value: "desert", label: "Desert" },
    { value: "forest", label: "Forest" },
    { value: "island", label: "Island" },
    { value: "mountains", label: "Mountains" },
    { value: "plains", label: "Plains" },
    { value: "swamp", label: "Swamp" },
  ],
  Skills: [
    { value: "Basic1", label: "Basic 1" },
    { value: "Basic2", label: "Basic 2" },
    { value: "Basic3", label: "Basic 3" },
    { value: "Basic4", label: "Basic 4" },
    { value: "Basic5", label: "Basic 5" },
    { value: "Basic6", label: "Basic 6" },
    { value: "Basic7", label: "Basic 7" },
    { value: "Basic8", label: "Basic 8" },
    { value: "Advanced1", label: "Advanced 1" },
    { value: "Advanced2", label: "Advanced 2" },
    { value: "Advanced3", label: "Advanced 3" },
    { value: "Advanced4", label: "Advanced 4" },
    { value: "Elite1", label: "Elite 1" },
    { value: "Elite2", label: "Elite 2" },
    { value: "Transcendent1", label: "Transcendent 1" },
  ],
  Professions: [
    { value: "mining", label: "Mining" },
    { value: "foraging", label: "Foraging" },
    { value: "gardening", label: "Gardening" },
    { value: "fishing", label: "Fishing" },
  ],
  StatNames: [
    { value: "Strength", label: "Strength" },
    { value: "Dexterity", label: "Dexterity" },
    { value: "Agility", label: "Agility" },
    { value: "Vitality", label: "Vitality" },
    { value: "Endurance", label: "Endurance" },
    { value: "Intelligence", label: "Intelligence" },
    { value: "Wisdom", label: "Wisdom" },
    { value: "Luck", label: "Luck" },
  ],
  StatBoosts: [
    { value: "STR", label: "STR" },
    { value: "DEX", label: "DEX" },
    { value: "AGI", label: "AGI" },
    { value: "VIT", label: "VIT" },
    { value: "END", label: "END" },
    { value: "INT", label: "INT" },
    { value: "WIS", label: "WIS" },
    { value: "LCK", label: "LCK" },
  ],
  Rarities: [
    { value: "Common", label: "Common" },
    { value: "Uncommon", label: "Uncommon" },
    { value: "Rare", label: "Rare" },
    { value: "Legendary", label: "Legendary" },
    { value: "Mythic", label: "Mythic" },
  ],
  Classes: [
    { value: "Seer", label: "Seer" },
    { value: "Berserker", label: "Berserker" },
    { value: "Warrior", label: "Warrior" },
    { value: "Knight", label: "Knight" },
    { value: "Thief", label: "Thief" },
    { value: "Archer", label: "Archer" },
    { value: "Pirate", label: "Pirate" },
    { value: "Monk", label: "Monk" },
    { value: "Priest", label: "Priest" },
    { value: "Wizard", label: "Wizard" },
    { value: "Shapeshifter", label: "Shapeshifter" },
    { value: "Paladin", label: "Paladin" },
    { value: "DarkKnight", label: "DarkKnight" },
    { value: "Ninja", label: "Ninja" },
    { value: "Summoner", label: "Summoner" },
    { value: "Dragoon", label: "Dragoon" },
    { value: "Sage", label: "Sage" },
    { value: "DreadKnight", label: "DreadKnight" },
  ],
  PJSurvivor: [
    { value: "SURVIVED", label: <PJBadge /> },
    { value: "DIED", label: "RIP" },
    { value: "null", label: "No" },
  ],
};
