export const greenEggData = [
 {
   "season": 0,
   "appearanceId": 1,
   "family": "Alpaca",
   "displayName": "Alpaca",
   "variant": "White",
   "rarity": 0,
   "pool": "Normal",
   "credits": "",
   "path": "Alpaca/Alpaca_White_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 2,
   "family": "Beanbug",
   "displayName": "Beanbug",
   "variant": "Green",
   "rarity": 0,
   "pool": "Normal",
   "credits": "",
   "path": "Beanbug/Beanbug_Green_Idle_v2.png"
 },
 {
   "season": 0,
   "appearanceId": 3,
   "family": "Beanbug",
   "displayName": "Beanbug",
   "variant": "Brown",
   "rarity": 0,
   "pool": "Normal",
   "credits": "",
   "path": "Beanbug/Beanbug_Brown_Idle_v2.png"
 },
 {
   "season": 0,
   "appearanceId": 4,
   "family": "Beanbug",
   "displayName": "Beanbug",
   "variant": "Red",
   "rarity": 0,
   "pool": "Normal",
   "credits": "",
   "path": "Beanbug/Beanbug_Red_Idle_v2.png"
 },
 {
   "season": 0,
   "appearanceId": 5,
   "family": "Beanbug",
   "displayName": "Beanbug",
   "variant": "Yellow",
   "rarity": 0,
   "pool": "Normal",
   "credits": "",
   "path": "Beanbug/Beanbug_Yellow_Idle_v2.png"
 },
 {
   "season": 0,
   "appearanceId": 6,
   "family": "Bellfries",
   "displayName": "Bellfry",
   "variant": "Violet",
   "rarity": 0,
   "pool": "Normal",
   "credits": "",
   "path": "Bellfry/Bellfry_Violet_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 7,
   "family": "Bellfries",
   "displayName": "Bellfry",
   "variant": "Red",
   "rarity": 0,
   "pool": "Normal",
   "credits": "",
   "path": "Bellfry/Bellfry_Red_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 8,
   "family": "Bellfries",
   "displayName": "Bellfry",
   "variant": "Green",
   "rarity": 0,
   "pool": "Normal",
   "credits": "",
   "path": "Bellfry/Bellfry_Green_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 9,
   "family": "Blubs",
   "displayName": "Blub",
   "variant": "Green",
   "rarity": 0,
   "pool": "Normal",
   "credits": "",
   "path": "Blubs/Blub_Green_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 10,
   "family": "Blubs",
   "displayName": "Blub",
   "variant": "Dark Green",
   "rarity": 0,
   "pool": "Normal",
   "credits": "",
   "path": "Blubs/Blub_DarkGreen_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 11,
   "family": "Blubs",
   "displayName": "Long Blub",
   "variant": "Green",
   "rarity": 0,
   "pool": "Normal",
   "credits": "",
   "path": "Blubs/LongBlub_Green_Idle_v2.png"
 },
 {
   "season": 0,
   "appearanceId": 12,
   "family": "Bocboc",
   "displayName": "Bocboc",
   "variant": "White",
   "rarity": 0,
   "pool": "Normal",
   "credits": "",
   "path": "Bocboc/Bocboc_White_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 13,
   "family": "Bocboc",
   "displayName": "Bocboc",
   "variant": "Brown",
   "rarity": 0,
   "pool": "Normal",
   "credits": "",
   "path": "Bocboc/Bocboc_Brown_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 14,
   "family": "Bun Buns",
   "displayName": "Bun",
   "variant": "Brown",
   "rarity": 0,
   "pool": "Normal",
   "credits": "",
   "path": "Bun/Bun_Brown_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 15,
   "family": "Bun Buns",
   "displayName": "Bun",
   "variant": "White",
   "rarity": 0,
   "pool": "Normal",
   "credits": "",
   "path": "Bun/Bun_White_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 16,
   "family": "Caterpillars",
   "displayName": "Caterpillar",
   "variant": "Green",
   "rarity": 0,
   "pool": "Normal",
   "credits": "",
   "path": "Caterpillar/Caterpillar_Green_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 17,
   "family": "Caterpillars",
   "displayName": "Caterpillar",
   "variant": "Yellow",
   "rarity": 0,
   "pool": "Normal",
   "credits": "",
   "path": "Caterpillar/Caterpillar_Yellow_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 18,
   "family": "Cow",
   "displayName": "Cow",
   "variant": "Brown",
   "rarity": 0,
   "pool": "Normal",
   "credits": "",
   "path": "Cows/Cow_Brown_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 19,
   "family": "Cow",
   "displayName": "Cow",
   "variant": "White",
   "rarity": 0,
   "pool": "Normal",
   "credits": "",
   "path": "Cows/Cow_White_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 20,
   "family": "Cow",
   "displayName": "Cow",
   "variant": "White 2",
   "rarity": 0,
   "pool": "Normal",
   "credits": "",
   "path": "Cows/Cow_White2_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 21,
   "family": "Garden Sprites",
   "displayName": "Baby Turnip",
   "variant": "Turnip",
   "rarity": 0,
   "pool": "Normal",
   "credits": "",
   "path": "GardenSprite/Turnip_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 22,
   "family": "Garden Sprites",
   "displayName": "Baby Carrot",
   "variant": "Carrot",
   "rarity": 0,
   "pool": "Normal",
   "credits": "",
   "path": "GardenSprite/Carrot_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 23,
   "family": "Garden Sprites",
   "displayName": "Baby Cabbage",
   "variant": "Cabbage",
   "rarity": 0,
   "pool": "Normal",
   "credits": "",
   "path": "GardenSprite/Cabbage_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 24,
   "family": "Hermit Grass",
   "displayName": "Hermit Grass",
   "variant": "Brown",
   "rarity": 0,
   "pool": "Normal",
   "credits": "",
   "path": "HermitGrass/HermitGrass_Brown_Idle_v2.png"
 },
 {
   "season": 0,
   "appearanceId": 25,
   "family": "Hermit Grass",
   "displayName": "Hermit Grass",
   "variant": "Grey",
   "rarity": 0,
   "pool": "Normal",
   "credits": "",
   "path": "HermitGrass/HermitGrass_Grey_Idle_v2.png"
 },
 {
   "season": 0,
   "appearanceId": 26,
   "family": "Scarecrow",
   "displayName": "Scarecrow",
   "variant": "Blue",
   "rarity": 0,
   "pool": "Normal",
   "credits": "",
   "path": "Scarecrow/Scarecrow_BlueHat_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 27,
   "family": "Snakes",
   "displayName": "Dwarf Snake",
   "variant": "Brown",
   "rarity": 0,
   "pool": "Normal",
   "credits": "",
   "path": "Snake/Snake_Brown_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 28,
   "family": "Snakes",
   "displayName": "Dwarf Snake",
   "variant": "Green",
   "rarity": 0,
   "pool": "Normal",
   "credits": "",
   "path": "Snake/Snake_Green_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 29,
   "family": "Greenhorn",
   "displayName": "Greenhorn",
   "variant": "White",
   "rarity": 0,
   "pool": "Normal",
   "credits": "",
   "path": "Greenhorn/Greenhorn_White_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 30,
   "family": "Alpaca",
   "displayName": "Fluffy Alpaca",
   "variant": "Fluffy",
   "rarity": 0,
   "pool": "Odd",
   "credits": "",
   "path": "Alpaca/Alpaca_FluffyWhite_Idle_v2.png"
 },
 {
   "season": 0,
   "appearanceId": 31,
   "family": "Beanbug",
   "displayName": "Jelly Beanbug",
   "variant": "Jelly",
   "rarity": 0,
   "pool": "Odd",
   "credits": "",
   "path": "Beanbug/Beanbug_Jelly_Idle_v2.png"
 },
 {
   "season": 0,
   "appearanceId": 32,
   "family": "Blubs",
   "displayName": "Veggie Blub",
   "variant": "Green",
   "rarity": 0,
   "pool": "Odd",
   "credits": "",
   "path": "Blubs/Blub_Green_Carrot_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 33,
   "family": "Snakes",
   "displayName": "Bubble Snake",
   "variant": "Water",
   "rarity": 0,
   "pool": "Odd",
   "credits": "",
   "path": "Snake/Snake_Water_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 34,
   "family": "Greenhorn",
   "displayName": "Hollowhorn",
   "variant": "Hollow",
   "rarity": 0,
   "pool": "Odd",
   "credits": "",
   "path": "Greenhorn/Greenhorn_Hollow_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 35,
   "family": "Alpaca",
   "displayName": "Alpacacorn",
   "variant": "Unicorn",
   "rarity": 0,
   "pool": "Odd",
   "credits": "",
   "path": "Alpaca/Alpacacorn_Idle_v2.png"
 },
 {
   "season": 0,
   "appearanceId": 36,
   "family": "Garden Sprite",
   "displayName": "Onion King",
   "variant": "Onion",
   "rarity": 0,
   "pool": "Ultra Odd",
   "credits": "",
   "path": "Ultraodd/Onion_Big_Idle_v2.png"
 },
 {
   "season": 0,
   "appearanceId": 37,
   "family": "Alpaca",
   "displayName": "Alpaca",
   "variant": "Black",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Alpaca/Alpaca_Black_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 38,
   "family": "Alpaca",
   "displayName": "Alpaca",
   "variant": "Blonde",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Alpaca/Alpaca_Blonde_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 39,
   "family": "Alpaca",
   "displayName": "Alpaca",
   "variant": "Brown",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Alpaca/Alpaca_Brown_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 40,
   "family": "Beetle",
   "displayName": "Beetle Hulk",
   "variant": "Red",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Beetle/Beetle_Red_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 41,
   "family": "Bellfries",
   "displayName": "Bellfry",
   "variant": "Blue",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Bellfry/Bellfry_Blue_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 42,
   "family": "Bellfries",
   "displayName": "Bellfry",
   "variant": "Orange",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Bellfry/Bellfry_Orange_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 43,
   "family": "Blubs",
   "displayName": "Long Blub",
   "variant": "Dark Green",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Blubs/LongBlub_DarkGreen_Idle_v2.png"
 },
 {
   "season": 0,
   "appearanceId": 44,
   "family": "Bocboc",
   "displayName": "Bocboc",
   "variant": "Yellow",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Bocboc/Bocboc_Yellow_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 45,
   "family": "Bun Buns",
   "displayName": "Big Bun",
   "variant": "Brown",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Fatbun/Fatbun_Brown_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 46,
   "family": "Bun Buns",
   "displayName": "Big Bun",
   "variant": "White",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Fatbun/Fatbun_White_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 47,
   "family": "Bun Buns",
   "displayName": "Bun",
   "variant": "Black",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Bun/Bun_Black_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 48,
   "family": "Caterpillars",
   "displayName": "Caterpillar",
   "variant": "Green/Red",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Caterpillar/Caterpillar_GreenRed_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 49,
   "family": "Cow",
   "displayName": "Cow",
   "variant": "Cow",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Cows/Cow_Black_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 50,
   "family": "Cow",
   "displayName": "Cow",
   "variant": "Orange",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Cows/Cow_Orange_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 51,
   "family": "Garden Sprites",
   "displayName": "Baby Strawberry",
   "variant": "Strawberry",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "GardenSprite/Strawberry_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 52,
   "family": "Gnomes",
   "displayName": "Garden Gnome",
   "variant": "Red",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Gnome/GardenGnome_Red_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 53,
   "family": "Hermit Grass",
   "displayName": "Hermit Grass",
   "variant": "Pink",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "HermitGrass/HermitGrass_Pink_Idle_v2.png"
 },
 {
   "season": 0,
   "appearanceId": 54,
   "family": "Manshrooms",
   "displayName": "Manshroom",
   "variant": "Red",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Manshroom/Manshroom_Red_Idle_v2.png"
 },
 {
   "season": 0,
   "appearanceId": 55,
   "family": "Manshrooms",
   "displayName": "Manshroom",
   "variant": "Brown",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Manshroom/Manshroom_Brown_Idle_v2.png"
 },
 {
   "season": 0,
   "appearanceId": 56,
   "family": "Manshrooms",
   "displayName": "Manshroom",
   "variant": "Green",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Manshroom/Manshroom_Green_Idle_v2.png"
 },
 {
   "season": 0,
   "appearanceId": 57,
   "family": "Primates",
   "displayName": "Ape",
   "variant": "Black",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Primates/Ape_Black_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 58,
   "family": "Primates",
   "displayName": "Ape",
   "variant": "Brown",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Primates/Ape_Brown_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 59,
   "family": "Primates",
   "displayName": "Monkey",
   "variant": "Black",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Primates/Monkey_Black_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 60,
   "family": "Primates",
   "displayName": "Monkey",
   "variant": "Red",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Primates/Monkey_Red_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 61,
   "family": "Scarecrow",
   "displayName": "Scarecrow",
   "variant": "Green",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Scarecrow/Scarecrow_GreenHat_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 62,
   "family": "Scarecrow",
   "displayName": "Scarecrow",
   "variant": "Orange",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Scarecrow/Scarecrow_OrangeHat_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 63,
   "family": "Snakes",
   "displayName": "Dwarf Snake",
   "variant": "Yellow",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Snake/Snake_Yellow_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 64,
   "family": "Snakes",
   "displayName": "Snake",
   "variant": "Brown",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Snake/LongSnake_Brown_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 65,
   "family": "Snakes",
   "displayName": "Snake",
   "variant": "Green",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Snake/LongSnake_Green_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 66,
   "family": "Snakes",
   "displayName": "Snake",
   "variant": "Yellow",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Snake/LongSnake_Yellow_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 67,
   "family": "Greenhorn",
   "displayName": "Greenhorn",
   "variant": "Green",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Greenhorn/Greenhorn_Green_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 68,
   "family": "Greenhorn",
   "displayName": "Greenhorn",
   "variant": "Blue",
   "rarity": 1,
   "pool": "Normal",
   "credits": "",
   "path": "Greenhorn/Greenhorn_Blue_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 69,
   "family": "Blubs",
   "displayName": "Long Veggie Blub",
   "variant": "Carrot",
   "rarity": 1,
   "pool": "Odd",
   "credits": "",
   "path": "Blubs/LongBlub_Green_Carrot_Idle_v2.png"
 },
 {
   "season": 0,
   "appearanceId": 70,
   "family": "Caterpillars",
   "displayName": "Badderpillar",
   "variant": "Demon",
   "rarity": 1,
   "pool": "Odd",
   "credits": "",
   "path": "Caterpillar/Caterpillar_Demon_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 71,
   "family": "Garden Sprites",
   "displayName": "Potato",
   "variant": "Potato",
   "rarity": 1,
   "pool": "Odd",
   "credits": "",
   "path": "GardenSprite/Potato_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 72,
   "family": "Hermit Grass",
   "displayName": "Festive Hermit Grass",
   "variant": "Flower",
   "rarity": 1,
   "pool": "Odd",
   "credits": "",
   "path": "HermitGrass/HermitGrass_BrownBlue_Idle_v2.png"
 },
 {
   "season": 0,
   "appearanceId": 73,
   "family": "Primates",
   "displayName": "Monkey Pirate",
   "variant": "Pirate",
   "rarity": 1,
   "pool": "Odd",
   "credits": "",
   "path": "Primates/Monkey_Pirate_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 74,
   "family": "Snakes",
   "displayName": "Ember Snake",
   "variant": "Flame",
   "rarity": 1,
   "pool": "Odd",
   "credits": "",
   "path": "Snake/LongSnake_Fire_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 75,
   "family": "Bocboc",
   "displayName": "Jade Babyboc",
   "variant": "Jade Chick",
   "rarity": 1,
   "pool": "Ultra Odd",
   "credits": "",
   "path": "Bocboc/Bocboc_JadeChick_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 76,
   "family": "Alpaca",
   "displayName": "Alpaca",
   "variant": "Strawberry",
   "rarity": 2,
   "pool": "Normal",
   "credits": "",
   "path": "Alpaca/Alpaca_Strawberry_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 77,
   "family": "Alpaca",
   "displayName": "Alpaca",
   "variant": "Violet",
   "rarity": 2,
   "pool": "Normal",
   "credits": "",
   "path": "Alpaca/Alpaca_Violet_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 78,
   "family": "Beetle",
   "displayName": "Beetle Hulk",
   "variant": "Black",
   "rarity": 2,
   "pool": "Normal",
   "credits": "",
   "path": "Beetle/Beetle_Black_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 79,
   "family": "Bocboc",
   "displayName": "Demon Bocboc",
   "variant": "Demon",
   "rarity": 2,
   "pool": "Normal",
   "credits": "",
   "path": "Bocboc/Bocboc_Evil_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 80,
   "family": "Bun Buns",
   "displayName": "Big Bun",
   "variant": "Pink",
   "rarity": 2,
   "pool": "Normal",
   "credits": "",
   "path": "Fatbun/Fatbun_Pink_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 81,
   "family": "Caterpillars",
   "displayName": "Giant Caterpillar",
   "variant": "Green",
   "rarity": 2,
   "pool": "Normal",
   "credits": "",
   "path": "Caterpillar/Caterpillar_Big_Green_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 82,
   "family": "Caterpillars",
   "displayName": "Giant Caterpillar",
   "variant": "Yellow",
   "rarity": 2,
   "pool": "Normal",
   "credits": "",
   "path": "Caterpillar/Caterpillar_Big_Yellow_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 83,
   "family": "Garden Sprites",
   "displayName": "Onion",
   "variant": "Onion",
   "rarity": 2,
   "pool": "Normal",
   "credits": "",
   "path": "GardenSprite/Onion_small_Idle_v2.png"
 },
 {
   "season": 0,
   "appearanceId": 84,
   "family": "Gnomes",
   "displayName": "Garden Gnome",
   "variant": "Blue",
   "rarity": 2,
   "pool": "Normal",
   "credits": "",
   "path": "Gnome/GardenGnome_Blue_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 85,
   "family": "Hermit Grass",
   "displayName": "Hermit Grass",
   "variant": "White Vase",
   "rarity": 2,
   "pool": "Normal",
   "credits": "",
   "path": "HermitGrass/HermitGrass_VaseWhite_Idle_v2.png"
 },
 {
   "season": 0,
   "appearanceId": 86,
   "family": "Impostor Dragon",
   "displayName": "Impostor Dragon",
   "variant": "Brown",
   "rarity": 2,
   "pool": "Normal",
   "credits": "",
   "path": "GardenDragon/GardenDragon_Thick_Brown_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 87,
   "family": "Manshrooms",
   "displayName": "Elder Manshroom",
   "variant": "Green",
   "rarity": 2,
   "pool": "Normal",
   "credits": "",
   "path": "Manshroom/Manshroom_ChubbyGreen_Idle_v2.png"
 },
 {
   "season": 0,
   "appearanceId": 88,
   "family": "Manshrooms",
   "displayName": "Elder Manshroom",
   "variant": "Red",
   "rarity": 2,
   "pool": "Normal",
   "credits": "",
   "path": "Manshroom/Manshroom_ChubbyRed_Idle_v2.png"
 },
 {
   "season": 0,
   "appearanceId": 89,
   "family": "Petalmen",
   "displayName": "Petal Buddy",
   "variant": "Red",
   "rarity": 2,
   "pool": "Normal",
   "credits": "",
   "path": "Petalers/Petal_Buddy_Red_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 90,
   "family": "Petalmen",
   "displayName": "Petal Buddy",
   "variant": "Yellow",
   "rarity": 2,
   "pool": "Normal",
   "credits": "",
   "path": "Petalers/Petal_Buddy_Yellow_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 91,
   "family": "Petalmen",
   "displayName": "Petal Buddy",
   "variant": "Blue",
   "rarity": 2,
   "pool": "Normal",
   "credits": "",
   "path": "Petalers/Petal_Buddy_Blue_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 92,
   "family": "Petalmen",
   "displayName": "Petal Buddy",
   "variant": "Purple",
   "rarity": 2,
   "pool": "Normal",
   "credits": "",
   "path": "Petalers/Petal_Buddy_Purple_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 93,
   "family": "Primates",
   "displayName": "Monkey",
   "variant": "White",
   "rarity": 2,
   "pool": "Normal",
   "credits": "",
   "path": "Primates/Monkey_White_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 94,
   "family": "Primates",
   "displayName": "Ape",
   "variant": "Red",
   "rarity": 2,
   "pool": "Normal",
   "credits": "",
   "path": "Primates/Ape_Red_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 95,
   "family": "Rocboc",
   "displayName": "Rocboc",
   "variant": "White",
   "rarity": 2,
   "pool": "Normal",
   "credits": "",
   "path": "Rocboc/Rocboc_White_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 96,
   "family": "Rocboc",
   "displayName": "Rocboc",
   "variant": "Brown",
   "rarity": 2,
   "pool": "Normal",
   "credits": "",
   "path": "Rocboc/Rocboc_Brown_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 97,
   "family": "Scarecrow",
   "displayName": "Scarecrow",
   "variant": "Red",
   "rarity": 2,
   "pool": "Normal",
   "credits": "",
   "path": "Scarecrow/Scarecrow_RedHat_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 98,
   "family": "Scarecrow",
   "displayName": "Scarecrow",
   "variant": "Yellow",
   "rarity": 2,
   "pool": "Normal",
   "credits": "",
   "path": "Scarecrow/Scarecrow_YellowHat_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 99,
   "family": "Snakes",
   "displayName": "Coiled Snake",
   "variant": "Brown",
   "rarity": 2,
   "pool": "Normal",
   "credits": "",
   "path": "Snake/CoiledSnake_Brown_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 100,
   "family": "Snakes",
   "displayName": "Coiled Snake",
   "variant": "Green",
   "rarity": 2,
   "pool": "Normal",
   "credits": "",
   "path": "Snake/CoiledSnake_Green_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 101,
   "family": "Snakes",
   "displayName": "Coiled Snake",
   "variant": "Yellow",
   "rarity": 2,
   "pool": "Normal",
   "credits": "",
   "path": "Snake/CoiledSnake_Yellow_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 102,
   "family": "Greenhorn",
   "displayName": "Greenhorn",
   "variant": "Pink",
   "rarity": 2,
   "pool": "Normal",
   "credits": "",
   "path": "Greenhorn/Greenhorn_Pink_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 103,
   "family": "Bocboc",
   "displayName": "Babyboc",
   "variant": "Yellow Chick",
   "rarity": 2,
   "pool": "Odd",
   "credits": "",
   "path": "Bocboc/Bocboc_Chick_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 104,
   "family": "Bun Buns",
   "displayName": "Zom Bun",
   "variant": "Zombie",
   "rarity": 2,
   "pool": "Odd",
   "credits": "",
   "path": "Fatbun/Fatbun_Zombie_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 105,
   "family": "Gnomes",
   "displayName": "Shovel Gnome",
   "variant": "Brown",
   "rarity": 2,
   "pool": "Odd",
   "credits": "",
   "path": "Gnome/GardenGnome_Brown_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 106,
   "family": "Manshrooms",
   "displayName": "Pop Pop Manshroom",
   "variant": "Red",
   "rarity": 2,
   "pool": "Odd",
   "credits": "",
   "path": "Manshroom/Manshroom_ChubbyRed_Odd_Idle_v2.png"
 },
 {
   "season": 0,
   "appearanceId": 107,
   "family": "Primates",
   "displayName": "Indifferent Ape",
   "variant": "Indifferent",
   "rarity": 2,
   "pool": "Odd",
   "credits": "",
   "path": "Primates/Ape_Indifferent_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 108,
   "family": "Snakes",
   "displayName": "Venomous Snake",
   "variant": "Poison",
   "rarity": 2,
   "pool": "Odd",
   "credits": "",
   "path": "Snake/CoiledSnake_Poison_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 109,
   "family": "Rocboc",
   "displayName": "Princess Rocboc",
   "variant": "Princess",
   "rarity": 2,
   "pool": "Ultra Odd",
   "credits": "",
   "path": "Rocboc/Rocboc_Pink_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 110,
   "family": "Alpaca",
   "displayName": "Alpaca",
   "variant": "Gold",
   "rarity": 3,
   "pool": "Normal",
   "credits": "",
   "path": "Alpaca/Alpaca_Gold_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 111,
   "family": "Beetle",
   "displayName": "Metal Hulk",
   "variant": "Metal",
   "rarity": 3,
   "pool": "Normal",
   "credits": "",
   "path": "Beetle/Beetle_Metal_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 112,
   "family": "Bun Buns",
   "displayName": "Bun",
   "variant": "Pink",
   "rarity": 3,
   "pool": "Normal",
   "credits": "",
   "path": "Bun/Bun_Pink_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 113,
   "family": "Caterpillars",
   "displayName": "Giant Caterpillar",
   "variant": "Green/Red",
   "rarity": 3,
   "pool": "Normal",
   "credits": "",
   "path": "Caterpillar/Caterpillar_Big_GreenRed_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 114,
   "family": "Garden Sprites",
   "displayName": "Mama Turnip",
   "variant": "Turnip",
   "rarity": 3,
   "pool": "Normal",
   "credits": "",
   "path": "GardenSprite/Turnip_Big_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 115,
   "family": "Gnomes",
   "displayName": "Garden Gnome",
   "variant": "Yellow",
   "rarity": 3,
   "pool": "Normal",
   "credits": "",
   "path": "Gnome/GardenGnome_Yellow_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 116,
   "family": "Gnomes",
   "displayName": "Garden Gnome",
   "variant": "Purple",
   "rarity": 3,
   "pool": "Normal",
   "credits": "",
   "path": "Gnome/GardenGnome_Purple_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 117,
   "family": "Gnomes",
   "displayName": "Planter Gnome",
   "variant": "Red",
   "rarity": 3,
   "pool": "Normal",
   "credits": "",
   "path": "Gnome/PlanterGnome_Red_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 118,
   "family": "Gnomes",
   "displayName": "Planter Gnome",
   "variant": "Brown",
   "rarity": 3,
   "pool": "Normal",
   "credits": "",
   "path": "Gnome/PlanterGnome_Brown_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 119,
   "family": "Gnomes",
   "displayName": "Planter Gnome",
   "variant": "Green",
   "rarity": 3,
   "pool": "Normal",
   "credits": "",
   "path": "Gnome/PlanterGnome_Green_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 120,
   "family": "Hermit Grass",
   "displayName": "Hermit Grass",
   "variant": "Brown Vase",
   "rarity": 3,
   "pool": "Normal",
   "credits": "",
   "path": "HermitGrass/HermitGrass_VaseBrown_Idle_v2.png"
 },
 {
   "season": 0,
   "appearanceId": 121,
   "family": "Impostor Dragon",
   "displayName": "Impostor Dragon",
   "variant": "Red",
   "rarity": 3,
   "pool": "Normal",
   "credits": "",
   "path": "GardenDragon/GardenDragon_Thick_Red_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 122,
   "family": "Leaf Dragon",
   "displayName": "Leaf Dragon",
   "variant": "Brown",
   "rarity": 3,
   "pool": "Normal",
   "credits": "",
   "path": "GardenDragon/GardenDragon_Brown_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 123,
   "family": "Leaf Dragon",
   "displayName": "Leaf Dragon",
   "variant": "Green",
   "rarity": 3,
   "pool": "Normal",
   "credits": "",
   "path": "GardenDragon/GardenDragon_Green_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 124,
   "family": "Manshrooms",
   "displayName": "Manshroom",
   "variant": "Purple",
   "rarity": 3,
   "pool": "Normal",
   "credits": "",
   "path": "Manshroom/Manshroom_Purple_Idle_v2.png"
 },
 {
   "season": 0,
   "appearanceId": 125,
   "family": "Petalmen",
   "displayName": "Petal Bloom",
   "variant": "Red",
   "rarity": 3,
   "pool": "Normal",
   "credits": "",
   "path": "Petalers/Petal_Bloom_Red_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 126,
   "family": "Petalmen",
   "displayName": "Petal Bloom",
   "variant": "Yellow",
   "rarity": 3,
   "pool": "Normal",
   "credits": "",
   "path": "Petalers/Petal_Bloom_Yellow_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 127,
   "family": "Petalmen",
   "displayName": "Petal Bloom",
   "variant": "Blue",
   "rarity": 3,
   "pool": "Normal",
   "credits": "",
   "path": "Petalers/Petal_Bloom_Blue_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 128,
   "family": "Primates",
   "displayName": "Ape",
   "variant": "White",
   "rarity": 3,
   "pool": "Normal",
   "credits": "",
   "path": "Primates/Ape_White_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 129,
   "family": "Rocboc",
   "displayName": "Rocboc",
   "variant": "Yellow",
   "rarity": 3,
   "pool": "Normal",
   "credits": "",
   "path": "Rocboc/Rocboc_Yellow_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 130,
   "family": "Scarecrow",
   "displayName": "Scarecrow",
   "variant": "Scary Green",
   "rarity": 3,
   "pool": "Normal",
   "credits": "",
   "path": "Scarecrow/Scarecrow_ScaryGreenHat_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 131,
   "family": "Scarecrow",
   "displayName": "Scarecrow",
   "variant": "Scary Red",
   "rarity": 3,
   "pool": "Normal",
   "credits": "",
   "path": "Scarecrow/Scarecrow_ScaryRedHat_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 132,
   "family": "Caterpillars",
   "displayName": "Cat-erpillar",
   "variant": "Cat",
   "rarity": 3,
   "pool": "Odd",
   "credits": "",
   "path": "Caterpillar/Caterpillar_Cat_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 133,
   "family": "Cow",
   "displayName": "Demon Cow",
   "variant": "Demon",
   "rarity": 3,
   "pool": "Odd",
   "credits": "",
   "path": "Cows/Cow_Demon_Idle_v2.png"
 },
 {
   "season": 0,
   "appearanceId": 134,
   "family": "Rocboc",
   "displayName": "Dire Rocboc",
   "variant": "Dire",
   "rarity": 3,
   "pool": "Odd",
   "credits": "",
   "path": "Rocboc/Rocboc_Dire_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 135,
   "family": "Gnomes",
   "displayName": "Blooming Gnome",
   "variant": "Flower",
   "rarity": 3,
   "pool": "Ultra Odd",
   "credits": "",
   "path": "Gnome/PlanterGnome_Flower_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 136,
   "family": "Beetle",
   "displayName": "Golden Hulk",
   "variant": "Gold",
   "rarity": 4,
   "pool": "Normal",
   "credits": "",
   "path": "Beetle/Beetle_Gold_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 137,
   "family": "Gnomes",
   "displayName": "Planter Gnome",
   "variant": "Orange",
   "rarity": 4,
   "pool": "Normal",
   "credits": "",
   "path": "Gnome/PlanterGnome_Orange_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 138,
   "family": "Leaf Dragon",
   "displayName": "Leaf Dragon",
   "variant": "Red",
   "rarity": 4,
   "pool": "Normal",
   "credits": "",
   "path": "GardenDragon/GardenDragon_Red_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 139,
   "family": "Leaf Dragon",
   "displayName": "Omega Leaf Dragon",
   "variant": "Brown",
   "rarity": 4,
   "pool": "Normal",
   "credits": "",
   "path": "GardenDragon/GardenDragon_Big_Brown_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 140,
   "family": "Petalmen",
   "displayName": "Petal Buster",
   "variant": "Blue",
   "rarity": 4,
   "pool": "Normal",
   "credits": "",
   "path": "Petalers/Petal_Buster_Blue_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 141,
   "family": "Petalmen",
   "displayName": "Petal Buster",
   "variant": "Red",
   "rarity": 4,
   "pool": "Normal",
   "credits": "",
   "path": "Petalers/Petal_Buster_Red_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 142,
   "family": "Cow",
   "displayName": "Sky Cow",
   "variant": "Sky",
   "rarity": 4,
   "pool": "Odd",
   "credits": "",
   "path": "Cows/Cow_Sky_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 143,
   "family": "Petalmen",
   "displayName": "Petal Champ",
   "variant": "Champ",
   "rarity": 4,
   "pool": "Odd",
   "credits": "",
   "path": "Petalers/Petal_Buster_Champ_Idle.png"
 },
 {
   "season": 0,
   "appearanceId": 144,
   "family": "Leaf Dragon",
   "displayName": "Abyssal Leaf Dragon",
   "variant": "Abyss",
   "rarity": 4,
   "pool": "Ultra Odd",
   "credits": "",
   "path": "GardenDragon/GardenDragon_Big_Abyss_Idle.png"
 }
]
